# Generated by Django 5.0.7 on 2024-07-25 16:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bazaar', '0010_auto_20211204_1650'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Customer',
        ),
    ]
